#!/usr/bin/env bash
set -e

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
FOXAR_DIR=${FOXAR_DIR:-"$BASE_DIR/.foxar"}
FOXAR_BIN_DIR="$FOXAR_DIR/bin"
FOXAR_MAN_DIR="$FOXAR_DIR/share/man/man1"

BINS=(spark probe shuttle pilot)

export RUSTFLAGS="-C target-cpu=native"

main() {
  need_cmd git
  need_cmd curl

  while [[ $1 ]]; do
    case $1 in
      --)               shift; break;;

      -r|--repo)        shift; FOXARUP_REPO=$1;;
      -b|--branch)      shift; FOXARUP_BRANCH=$1;;
      -v|--version)     shift; FOXARUP_VERSION=$1;;
      -p|--path)        shift; FOXARUP_LOCAL_REPO=$1;;
      -P|--pr)          shift; FOXARUP_PR=$1;;
      -C|--commit)      shift; FOXARUP_COMMIT=$1;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        warn "unknown option: $1"
        usage
        exit 1
    esac; shift
  done

  # Print the banner after successfully parsing args
  banner

  if [ -n "$FOXARUP_PR" ]; then
    if [ -z "$FOXARUP_BRANCH" ]; then
      FOXARUP_BRANCH="refs/pull/$FOXARUP_PR/head"
    else
      err "can't use --pr and --branch at the same time"
    fi
  fi

  # Installs foxar from a local repository if --path parameter is provided
  if [[ -n "$FOXARUP_LOCAL_REPO" ]]; then
    need_cmd cargo

    # Ignore branches/versions as we do not want to modify local git state
    if [ -n "$FOXARUP_REPO" ] || [ -n "$FOXARUP_BRANCH" ] || [ -n "$FOXARUP_VERSION" ]; then
      warn "--branch, --version, and --repo arguments are ignored during local install"
    fi

    # Enter local repo and build
    say "installing from $FOXARUP_LOCAL_REPO"
    cd "$FOXARUP_LOCAL_REPO"
    ensure cargo build --release # need 4 speed

    for bin in "${BINS[@]}"; do
      # Remove prior installations if they exist
      rm -f "$FOXAR_BIN_DIR/$bin"
      # Symlink from local repo binaries to bin dir
      ensure ln -s "$PWD/target/release/$bin" "$FOXAR_BIN_DIR/$bin"
    done

    say "done"
    exit 0
  fi

  FOXARUP_REPO=${FOXARUP_REPO:-bchainhub/foxar}

  # Install by downloading binaries
  if [[ "$FOXARUP_REPO" == "bchainhub/foxar" && -z "$FOXARUP_BRANCH" && -z "$FOXARUP_COMMIT" ]]; then
    FOXARUP_VERSION=${FOXARUP_VERSION:-nightly}
    FOXARUP_TAG=$FOXARUP_VERSION

    # Normalize versions (handle channels, versions without v prefix
    if [[ "$FOXARUP_VERSION" == "nightly" ]]; then
      # Locate real nightly tag
      SHA=$(ensure curl -sSf "https://api.github.com/repos/$FOXARUP_REPO/git/refs/tags/nightly" \
        | grep -Eo '"sha"[^,]*' \
        | grep -Eo '[^:]*$' \
        | tr -d '"' \
        | tr -d ' ' \
        | cut -d ':' -f2 )
      FOXARUP_TAG="nightly-${SHA}"
    elif [[ "$FOXARUP_VERSION" == nightly* ]]; then
      FOXARUP_VERSION="nightly"
    elif [[ "$FOXARUP_VERSION" == [[:digit:]]* ]]; then
      # Add v prefix
      FOXARUP_VERSION="v${FOXARUP_VERSION}"
      FOXARUP_TAG="${FOXARUP_VERSION}"
    fi

    say "installing foxar (version ${FOXARUP_VERSION}, tag ${FOXARUP_TAG})"

    PLATFORM="$(uname -s)"
    EXT="tar.gz"
    case $PLATFORM in
      Linux)
        PLATFORM="linux"
        ;;
      Darwin)
        PLATFORM="darwin"
        ;;
      MINGW*)
        EXT="zip"
        PLATFORM="win32"
        ;;
      *)
        err "unsupported platform: $PLATFORM"
        ;;
    esac

    ARCHITECTURE="$(uname -m)"
    if [ "${ARCHITECTURE}" = "x86_64" ]; then
      # Redirect stderr to /dev/null to avoid printing errors if non Rosetta.
      if [ "$(sysctl -n sysctl.proc_translated 2>/dev/null)" = "1" ]; then
        ARCHITECTURE="arm64" # Rosetta.
      else
        ARCHITECTURE="amd64" # Intel.
      fi
    elif [ "${ARCHITECTURE}" = "arm64" ] ||[ "${ARCHITECTURE}" = "aarch64" ] ; then
      ARCHITECTURE="arm64" # Arm.
    else
      ARCHITECTURE="amd64" # Amd.
    fi

    # Compute the URL of the release tarball in the Foxar repository.
    RELEASE_URL="https://github.com/${FOXARUP_REPO}/releases/download/${FOXARUP_TAG}/"
    BIN_ARCHIVE_URL="${RELEASE_URL}foxar_${FOXARUP_VERSION}_${PLATFORM}_${ARCHITECTURE}.$EXT"
    MAN_TARBALL_URL="${RELEASE_URL}foxar_man_${FOXARUP_VERSION}.tar.gz"

    # Download and extract the binaries archive
    say "downloading latest spark, probe, shuttle, and pilot"
    if [ "$PLATFORM" = "win32" ]; then
      tmp="$(mktemp -d 2>/dev/null || echo ".")/foxar.zip"
      ensure download "$BIN_ARCHIVE_URL" "$tmp"
      ensure unzip "$tmp" -d "$FOXAR_BIN_DIR"
      rm -f "$tmp"
    else
      ensure download "$BIN_ARCHIVE_URL" | ensure tar -xzC "$FOXAR_BIN_DIR"
    fi

    # Optionally download the manuals
    if check_cmd tar; then
      say "downloading manpages"
      mkdir -p "$FOXAR_MAN_DIR"
      download "$MAN_TARBALL_URL" | tar -xzC "$FOXAR_MAN_DIR"
    else
      say 'skipping manpage download: missing "tar"'
    fi

    for bin in "${BINS[@]}"; do
      bin_path="$FOXAR_BIN_DIR/$bin"

      # Print installed msg
      say "installed - $(ensure "$bin_path" --version)"

      # Check if the default path of the binary is not in FOXAR_BIN_DIR
      which_path="$(which "$bin")"
      if [ "$which_path" != "$bin_path" ]; then
        warn ""
        cat 1>&2 <<EOF
There are multiple binaries with the name '$bin' present in your 'PATH'.
This may be the result of installing '$bin' using another method,
like Cargo or other package managers.
You may need to run 'rm $which_path' or move '$FOXAR_BIN_DIR'
in your 'PATH' to allow the newly installed version to take precedence!

EOF
      fi
    done

    say "done!"

  # Install by cloning the repo with the provided branch/tag
  else
    need_cmd cargo
    FOXARUP_BRANCH=${FOXARUP_BRANCH:-master}
    REPO_PATH="$FOXAR_DIR/$FOXARUP_REPO"

    # If repo path does not exist, grab the author from the repo, make a directory in .foxar, cd to it and clone.
    if [ ! -d "$REPO_PATH" ]; then
      AUTHOR="$(echo "$FOXARUP_REPO" | cut -d'/' -f1 -)"
      ensure mkdir -p "$FOXAR_DIR/$AUTHOR"
      cd "$FOXAR_DIR/$AUTHOR"
      ensure git clone "https://github.com/$FOXARUP_REPO"
    fi

    # Force checkout, discarding any local changes
    cd "$REPO_PATH"
    ensure git fetch origin "${FOXARUP_BRANCH}:remotes/origin/${FOXARUP_BRANCH}"
    ensure git checkout "origin/${FOXARUP_BRANCH}"

    # If set, checkout specific commit from branch
    if [ -n "$FOXARUP_COMMIT" ]; then
      say "installing at commit $FOXARUP_COMMIT"
      ensure git checkout "$FOXARUP_COMMIT"
    fi

    # Build the repo and install the binaries locally to the .foxar bin directory.
    # --root appends /bin to the directory it is given, so we pass FOXAR_DIR.
    ensure cargo install --path ./cli --bins --locked --force --root "$FOXAR_DIR"
    # install shuttle
    ensure cargo install --path ./shuttle --bin shuttle --locked --force --root "$FOXAR_DIR"
    # install pilot
    ensure cargo install --path ./pilot --bin pilot --locked --force --root "$FOXAR_DIR"

    # If help2man is installed, use it to add Foxar man pages.
    if check_cmd help2man; then
      for bin in "${BINS[@]}"; do
        help2man -N "$FOXAR_BIN_DIR/$bin" > "$FOXAR_MAN_DIR/$bin.1"
      done
    fi

    say "done"
  fi
}

usage() {
  cat 1>&2 <<EOF
The installer for Foxar.

Update or revert to a specific Foxar version with ease.

USAGE:
    foxarup <OPTIONS>

OPTIONS:
    -h, --help      Print help information
    -v, --version   Install a specific version
    -b, --branch    Install a specific branch
    -P, --pr        Install a specific Pull Request
    -C, --commit    Install a specific commit
    -r, --repo      Install from a remote GitHub repo (uses default branch if no other options are set)
    -p, --path      Install a local repository
EOF
}

say() {
  printf "foxarup: %s\n" "$1"
}

warn() {
  say "warning: ${1}" >&2
}

err() {
  say "$1" >&2
  exit 1
}

need_cmd() {
  if ! check_cmd "$1"; then
    err "need '$1' (command not found)"
  fi
}

check_cmd() {
  command -v "$1" &>/dev/null
}

# Run a command that should never fail. If the command fails execution
# will immediately terminate with an error showing the failing
# command.
ensure() {
  if ! "$@"; then err "command failed: $*"; fi
}

# Downloads $1 into $2 or stdout
download() {
  if [ "$2" ]; then
    # output into $2
    if check_cmd curl; then
      curl -#o "$2" -L "$1"
    else
      wget --show-progress -qO "$2" "$1"
    fi
  else
    # output to stdout
    if check_cmd curl; then
      curl -#L "$1"
    else
      wget --show-progress -qO- "$1"
    fi
  fi
}

# Banner Function for Foxar 
banner() {
  printf '
  FOXAR INSTALLED
'
}


main "$@" || exit 1
