#!/usr/bin/env bash
set -e

echo Installing foxarup...

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
FOXAR_DIR=${FOXAR_DIR-"$BASE_DIR/.foxar"}
FOXAR_BIN_DIR="$FOXAR_DIR/bin"
FOXAR_MAN_DIR="$FOXAR_DIR/share/man/man1"

BIN_URL="https://raw.githubusercontent.com/bchainhub/foundry/master/foxarup/foxarup"
BIN_PATH="$FOXAR_BIN_DIR/foxarup"


# Create the .foxar bin directory and foxarup binary if it doesn't exist.
mkdir -p $FOXAR_BIN_DIR
curl -# -L $BIN_URL -o $BIN_PATH
chmod +x $BIN_PATH

# Create the man directory for future man files if it doesn't exist.
mkdir -p $FOXAR_MAN_DIR

# Store the correct profile file (i.e. .profile for bash or .zshenv for ZSH).
case $SHELL in
*/zsh)
    PROFILE=${ZDOTDIR-"$HOME"}/.zshenv
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
*/ash)
    PROFILE=$HOME/.profile
    PREF_SHELL=ash
    ;;
*)
    echo "foxarup: could not detect shell, manually add ${FOXAR_BIN_DIR} to your PATH."
    exit 1
esac

# Only add foxarup if it isn't already in PATH.
if [[ ":$PATH:" != *":${FOXAR_BIN_DIR}:"* ]]; then
    # Add the foxarup directory to the path and ensure the old PATH variables remain.
    echo >> $PROFILE && echo "export PATH=\"\$PATH:$FOXAR_BIN_DIR\"" >> $PROFILE
fi

# Warn MacOS users that they may need to manually install libusb via Homebrew:
if [[ "$OSTYPE" =~ ^darwin ]] && [[ ! -f /usr/local/opt/libusb/lib/libusb-1.0.0.dylib && ! -f /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib ]]; then
    echo && echo "warning: libusb not found. You may need to install it manually on MacOS via Homebrew (brew install libusb)."
fi

echo && echo "Detected your preferred shell is ${PREF_SHELL} and added foxarup to PATH. Run 'source ${PROFILE}' or start a new terminal session to use foxarup."
echo "Then, simply run 'foxarup' to install Foxar."
