[package]
name = "spark-doc"
version = "0.1.0"
edition = "2021"
description = """
Foxar's solidity doc parsing
"""
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
# foxar internal
foxar-common = { path = "../common" }
spark-fmt = { path = "../fmt" }
foxar-config = { path = "../config" }
foxar-utils = { path = "../utils" }

# corebc
corebc-ylem = { workspace = true, features = ["async"]}
corebc-core = { workspace = true}

# cli
clap = { version = "4", features = ["derive", "env", "unicode", "wrap_help"] }

# tracing
tracing = "0.1"

# mdbook
mdbook = { version = "0.4", default-features = false, features = ["search"] }
warp = { version = "0.3", default-features = false, features = ["websocket"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
futures-util = "0.3"

# misc
solang-parser.workspace = true
eyre = "0.6"
thiserror = "1"
rayon = "1"
itertools = "0.10"
toml = "0.7"
auto_impl = "1"
derive_more = "0.99"
once_cell = "1"
serde = "1.0.163"
serde_json = "1.0.96"
